version: 2
jobs:
  build:
    working_directory: ~/stripe-customers-fetcher
    docker:
      - image: circleci/ruby:3.1.2
        environment:
          BUNDLER_VERSION: 2.3.3
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rspec
